import type { AIProviderConfig } from "@/types";

export const AI_PROVIDERS: AIProviderConfig[] = [
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    isEnabled: false,
    color: "#10a37f",
    icon: "openai",
    models: [
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        provider: "openai",
        contextWindow: 128_000,
        inputCostPer1k: 0.00015,
        outputCostPer1k: 0.0006,
        supportsStreaming: true,
        supportsVision: true,
        isFree: false,
      },
      {
        id: "gpt-4o",
        name: "GPT-4o",
        provider: "openai",
        contextWindow: 128_000,
        inputCostPer1k: 0.005,
        outputCostPer1k: 0.015,
        supportsStreaming: true,
        supportsVision: true,
        isFree: false,
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    isEnabled: false,
    color: "#d97757",
    icon: "anthropic",
    models: [
      {
        id: "claude-haiku-4-5-20251001",
        name: "Claude Haiku 4.5",
        provider: "anthropic",
        contextWindow: 200_000,
        inputCostPer1k: 0.00025,
        outputCostPer1k: 0.00125,
        supportsStreaming: true,
        supportsVision: true,
        isFree: false,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        provider: "anthropic",
        contextWindow: 200_000,
        inputCostPer1k: 0.003,
        outputCostPer1k: 0.015,
        supportsStreaming: true,
        supportsVision: true,
        isFree: false,
      },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    isEnabled: false,
    color: "#4285f4",
    icon: "gemini",
    models: [
      {
        id: "gemini-2.0-flash-exp",
        name: "Gemini 2.0 Flash (Free)",
        provider: "gemini",
        contextWindow: 1_000_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: true,
        isFree: true,
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash (Free)",
        provider: "gemini",
        contextWindow: 1_000_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: true,
        isFree: true,
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    isEnabled: false,
    color: "#f55036",
    icon: "groq",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B (Free tier)",
        provider: "groq",
        contextWindow: 128_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: false,
        isFree: true,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B (Free tier)",
        provider: "groq",
        contextWindow: 32_768,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: false,
        isFree: true,
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    isEnabled: false,
    color: "#0066ff",
    icon: "deepseek",
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        provider: "deepseek",
        contextWindow: 64_000,
        inputCostPer1k: 0.00014,
        outputCostPer1k: 0.00028,
        supportsStreaming: true,
        supportsVision: false,
        isFree: false,
      },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    isEnabled: false,
    color: "#7c3aed",
    icon: "openrouter",
    models: [
      {
        id: "meta-llama/llama-3.1-8b-instruct:free",
        name: "Llama 3.1 8B (Free)",
        provider: "openrouter",
        contextWindow: 128_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: false,
        isFree: true,
      },
      {
        id: "mistralai/mistral-7b-instruct:free",
        name: "Mistral 7B (Free)",
        provider: "openrouter",
        contextWindow: 32_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: false,
        isFree: true,
      },
    ],
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    baseUrl: "http://localhost:11434/v1",
    isEnabled: false,
    color: "#888888",
    icon: "ollama",
    models: [
      {
        id: "llama3.2",
        name: "Llama 3.2 (Local)",
        provider: "ollama",
        contextWindow: 128_000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        supportsStreaming: true,
        supportsVision: false,
        isFree: true,
      },
    ],
  },
];

export const getProviderById = (id: string) =>
  AI_PROVIDERS.find((p) => p.id === id);

export const getFreeModels = () =>
  AI_PROVIDERS.flatMap((p) => p.models.filter((m) => m.isFree));
